<?php

namespace Microsoft\BingAds\V13\CampaignManagement;

{
    /**
     * Reserved.
     * @link https:/learn.microsoft.com/advertising/campaign-management-service/aisearchsetting?view=bingads-13 AISearchSetting Data Object
     */
    final class AISearchSetting extends Setting
    {
        /**
         * Reserved.
         * @var boolean
         */
        public $AISearchEnabled;

        /**
         * Reserved.
         * @var boolean
         */
        public $AutoGeneratedImageOptOut;

        /**
         * Reserved.
         * @var boolean
         */
        public $AutoGeneratedTextOptOut;

        /**
         * Reserved.
         * @var boolean
         */
        public $FinalUrlExpansionOptOut;

        /**
         * Reserved.
         * @var boolean
         */
        public $SearchTermMatchingOptOut;
    }

}
