<?php

namespace Microsoft\BingAds\V13\CampaignManagement;

{
    /**
     * Enable or opt out of AI search settings.
     * @link https:/learn.microsoft.com/advertising/campaign-management-service/aisearchsetting?view=bingads-13 AISearchSetting Data Object
     */
    final class AISearchSetting extends Setting
    {
        /**
         * Enable AI search.
         * @var boolean
         */
        public $AISearchEnabled;

        /**
         * Opt out of auto-generated images.
         * @var boolean
         */
        public $AutoGeneratedImageOptOut;

        /**
         * Opt out of auto-generated text.
         * @var boolean
         */
        public $AutoGeneratedTextOptOut;

        /**
         * Opt out of final URL expansion.
         * @var boolean
         */
        public $FinalUrlExpansionOptOut;

        /**
         * Reserved.
         * @var integer[]
         */
        public $PageFeedIds;

        /**
         * Opt out of search term matching.
         * @var boolean
         */
        public $SearchTermMatchingOptOut;
    }

}
