<?php

namespace Microsoft\BingAds\V13\CampaignManagement;

{
    /**
     * Reserved.
     * @link https:/learn.microsoft.com/advertising/campaign-management-service/performancemaxsetting?view=bingads-13 PerformanceMaxSetting Data Object
     */
    final class PerformanceMaxSetting extends Setting
    {
        public $AutoGeneratedImageOptOut;
        public $AutoGeneratedTextOptOut;
        public $CostPerSaleOptOut;

        /**
         * Reserved.
         * @var boolean
         */
        public $FinalUrlExpansionOptOut;
        public $PageFeedIds;
    }

}
