<?php

namespace Microsoft\BingAds\V13\CampaignManagement;

{
    /**
     * Reserved.
     * @link https://docs.microsoft.com/en-us/advertising/campaign-management-service/responsivesearchadssetting?view=bingads-13 ResponsiveSearchAdsSetting Data Object
     */
    final class ResponsiveSearchAdsSetting extends Setting
    {
        /**
         * Reserved.
         * @var boolean
         */
        public $AutoGeneratedAssetsEnabled;
    }

}
