<?php

namespace Microsoft\BingAds\V13\CampaignManagement;

{
    /**
     * Defines the ResponsiveSearchAdsSetting object.
     * @link https:/learn.microsoft.com/advertising/campaign-management-service/responsivesearchadssetting?view=bingads-13 ResponsiveSearchAdsSetting Data Object
     */
    final class ResponsiveSearchAdsSetting extends Setting
    {
        /**
         * Not everyone has this feature yet.
         * @var boolean
         */
        public $AutoGeneratedAssetsEnabled;
    }

}
