<?php

namespace Microsoft\BingAds\V13\CampaignManagement;

{
    /**
     * Defines the unified automation setting data object.
     * @link https://learn.microsoft.com/en-us/advertising/campaign-management-service/unifiedautomationsetting?view=bingads-13 UnifiedAutomationSetting Data Object
     */
    final class UnifiedAutomationSetting extends Setting
    {
        /**
         * Opt out of audience optimization.
         * @var boolean
         */
        public $AudienceOptimizationOptOut;

        /**
         * Opt out of auto-generated images.
         * @var boolean
         */
        public $AutoGeneratedImageOptOut;

        /**
         * Opt out of auto-generated text.
         * @var boolean
         */
        public $AutoGeneratedTextOptOut;

        /**
         * Opt out of channel optimization.
         * @var boolean
         */
        public $ChannelOptimizationOptOut;

        /**
         * Opt out of final URL expansion.
         * @var boolean
         */
        public $FinalUrlExpansionOptOut;

        /**
         * Opt out search term matching.
         * @var boolean
         */
        public $SearchTermMatchingOptOut;
    }

}
