<?php

namespace Microsoft\BingAds\V13\Reporting;

{
    /**
     * |Defines the attributes and performance statistics columns that you can include in the AssetPerformanceReportRequest.
     * @link https:/learn.microsoft.com/advertising/reporting-service/assetperformancereportcolumn?view=bingads-13 AssetPerformanceReportColumn Value Set
     * 
     * @used-by AssetPerformanceReportRequest
     */
    final class AssetPerformanceReportColumn
    {
        /** The time period of each report row. */
        const TimePeriod = 'TimePeriod';

        /** The Microsoft Advertising assigned identifier of an account. */
        const AccountId = 'AccountId';

        /** The account name. */
        const AccountName = 'AccountName';

        /** The Microsoft Advertising assigned identifier of a campaign. */
        const CampaignId = 'CampaignId';

        /** The campaign name. */
        const CampaignName = 'CampaignName';

        /** The Microsoft Advertising assigned identifier of an ad group. */
        const AdGroupId = 'AdGroupId';

        /** The ad group name. */
        const AdGroupName = 'AdGroupName';

        /** The Microsoft Advertising assigned identifier of an asset. */
        const AssetId = 'AssetId';

        /** The content of the asset. */
        const AssetContent = 'AssetContent';

        /** A string that indicates the role this asset plays in the ad (e.g, Headline, Description, Call to Action, Image). */
        const AssetType = 'AssetType';

        /** A string, which is either "Advertiser Provided" or "Autogenerated", which indicates the source of the asset. */
        const AssetSource = 'AssetSource';

        /** The number of times an ad has been displayed on search results pages. */
        const Impressions = 'Impressions';

        /** Clicks are what you pay for. */
        const Clicks = 'Clicks';

        /** The click-through rate (CTR) is the number of times an ad was clicked, divided by the number of times the ad was shown (impressions). */
        const Ctr = 'Ctr';

        /** The cost per click (CPC) summed for each click. */
        const Spend = 'Spend';
    }

}
